- hosts: localhost
  vars: 
    - admin_base_url: "http://192.168.99.100:8001"
    - api_base_url: "http://192.168.99.100:8000"
  
  tasks:
    
    - name: Register APIs
      kong_api:
        kong_admin_uri: "{{admin_base_url}}"     
        name: "{{item.name}}"
        upstream_url: "{{item.upstream_url}}"
        hosts: "{{item.hosts}}"
        state: present
        uris: "{{item.uris}}"
      with_items:
        - name: "mockbin"
          upstream_url: "http://mockbin.com"
          hosts: "mockbin.com"
          uris: "/mockbin"
          strip_uri: yes
      register: response

    - debug: var=response